;Wasp Nest
;by Alexander Burtzev
;Union of Soviet Socialist Republics
;
ORG	20
MOV.I	$19,	<18
MOV.I	$9,	<17
MOV.I	<7,	<16
SUB.F	<6,	<6
JMP.B	@14,	$0
DAT.F	#0,	$4000
MOV.I	$-1,	<-1
DJN.B	$-1,	<-2
SPL.B	$-2,	$0
JMP.B	$-1,	$0
JMP.B	$-1,	$0
JMP.B	$-1,	$0
JMP.B	$-1,	$0
JMP.B	$-1,	$0
JMP.B	$-1,	$0
JMP.B	$-1,	$0
JMP.B	$-1,	$0
JMP.B	$-1,	$0
JMP.B	$-1,	$0
JMP.B	$-1,	$0
MOV.AB	#-223,	$-1
MOV.AB	#0,	$-12
;
ADD.AB	#-1407,	$-4
SPL.B	$10,	$0
SPL.B	$10,	$0
SPL.B	$10,	$0
SPL.B	$10,	$0
SPL.B	$10,	$0
SPL.B	$10,	$0
SPL.B	$10,	$0
SPL.B	$10,	$0
SPL.B	$10,	$0
JMP.B	$10,	$0
JMP.B	$1,	$0
JMP.B	$1,	$0
JMP.B	$1,	$0
JMP.B	$1,	$0
JMP.B	$1,	$0
JMP.B	$1,	$0
JMP.B	$1,	$0
JMP.B	$1,	$0
JMP.B	$-41,	$0
JMP.B	$1,	$0
JMP.B	$1,	$0
JMP.B	$1,	$0
DJN.B	$-24,	$4
MOV.AB	#-1000,	$3
MOV.I	$2,	<2
DJN.B	$-1,	<1
DAT.F	#0,	$7
