;redcode-88
;name Nameless
;author Blameless
ORG	4
DAT.F	#0,	#1588
DAT.F	#0,	#1337
DAT.F	#0,	#123
SPL.B	$0,	$0
SPL.B	$17,	$0
CMP.I	<-5,	<-4
MOV.I	$-3,	@-6
CMP.I	<-7,	<-6
MOV.I	$-5,	@-7
DJN.B	$-4,	$-7
MOV.AB	#1589,	$-10
MOV.AB	#168,	$-9
MOV.I	$-12,	<-12
MOV.I	$-13,	<-13
MOV.I	$-14,	<-14
DJN.B	$-3,	$-13
JMP.B	$-6,	$0
DAT.F	#0,	#1588
DAT.F	#0,	#1337
DAT.F	#0,	#123
SPL.B	$0,	$0
SPL.B	$17,	$0
CMP.I	<-5,	<-4
MOV.I	$-3,	@-6
CMP.I	<-7,	<-6
MOV.I	$-5,	@-7
DJN.B	$-4,	$-7
MOV.AB	#1589,	$-10
MOV.AB	#168,	$-9
MOV.I	$-12,	<-12
MOV.I	$-13,	<-13
MOV.I	$-14,	<-14
DJN.B	$-3,	$-13
JMP.B	$-6,	$0
